#!/usr/bin/env python3
#show all available ips
from os import system
from subprocess import Popen,PIPE
import re

exp = r'\d: (.*): '

def all_interfaces():
    cmd = 'ip addr show'
    out = Popen(cmd,shell=True,stdout=PIPE,stderr=PIPE,stdin=PIPE).stdout.read()
    return re.findall(exp,out.decode())
    

def main():
    for interface in all_interfaces():
       out = Popen('ip addr show '+interface,stdout=PIPE,shell=True).stdout.read().decode()
       ip = re.findall('([0-9\.]+)/',out)
       if ip:
            print(f'{interface} : {ip[0]}')
if __name__ == '__main__':
    main()
